Repository Mod-Sim/Image-Bot, pull requests merged in 2022-04, with the labels that each got.

#1 Basic Bot Functionality
  .gitignore
  README.md
  commands/ping.js
  deploy-commands.js
  events/interactionCreate.js
  events/ready.js
  index.js
  package-lock.json
  package.json
Labels: enhancement

#9 Deploy commands
  .github/workflows/deploy-commands.yml
  commands-dev/ping.js
  deploy-commands.js
  index.js
  package.json
Labels: bug, enhancement

#11 Update readme
  README.md
Labels: enhancement

#13 Search api
  commands/search.js
  image_search.js
  package-lock.json
  package.json
Labels: enhancement

#20 Update readme
  README.md
Labels: documentation

#17 Create PROCESS.md
  PROCESS.md
  README.md
Labels: documentation
